on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.0
      - run: CGO_ENABLED=1 go build -tags=plugin -o monomer_linux_amd64.so
      - uses: softprops/action-gh-release@v1
        with:
          files: monomer_linux_amd64.vst

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.0
      - run: go build -tags=plugin -o monomer_windows_amd64.dll
        env:
          CGO_ENABLED: 1
      - uses: softprops/action-gh-release@v1
        with:
          files: monomer_windows_amd64.dll

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.0
      - run: |
          CGO_ENABLED=1 go build -tags=plugin -o monomer_macos_amd64.vst
          CGO_ENABLED=1 GOARCH=arm64 go build -tags=plugin -o monomer_macos_arm64.vst
        env:
          GOOS: darwin
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            monomer_macos_amd64.vst
            monomer_macos_arm64.vst
