on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  build-linux-windows:
    name: Build Linux & Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.0
      - name: Build Linux
        run: CGO_ENABLED=1 go build -tags=plugin --buildmode=c-shared -o monomer_linux_amd64.so
      - name: Build Windows
        run: CGO_ENABLED=1 GOOS=windows CC=x86_64-w64-mingw32-gcc go build -tags=plugin --buildmode=c-shared -ldflags="-extldflags "-static"" -o monomer_windows_amd64.dll
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            monomer_linux_amd64.so
            monomer_windows_amd64.dll

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17.0
      - name: Build macOS
        run: |
          CGO_ENABLED=1 go build -tags=plugin --buildmode=c-shared -o monomer_macos_amd64.vst
          CGO_ENABLED=1 GOARCH=arm64 go build -tags=plugin --buildmode=c-shared -o monomer_macos_arm64.vst
        env:
          GOOS: darwin
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            monomer_macos_amd64.vst
            monomer_macos_arm64.vst
